<a href="https://colab.research.google.com/github/sanjibsinha/pythonforethicalhacking/blob/main/NumPyOne.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 8])

mat = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[1 2 3 4 8]


In [ ]:
print(mat)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(arr[2])

3


In [ ]:
print(mat[1, 1])

5


In [ ]:
arr = np.array([1, 2, 3, 4, 8])

sum_arr = arr + 2

print(sum_arr)

[ 3  4  5  6 10]


In [ ]:
greater_than_3 = arr > 3

print(greater_than_3)

[False False False  True  True]


In [ ]:
sin_arr = np.sin(arr)

print(sin_arr)

[ 0.84147098  0.90929743  0.14112001 -0.7568025   0.98935825]


In [ ]:
mean_arr = np.mean(arr)

print(mean_arr)

3.6


In [ ]:
sq_arr = arr ** 2

print(sq_arr)

[ 1  4  9 16 64]


In [ ]:
cube_arr = arr ** 3

print(cube_arr)

[  1   8  27  64 512]
